### PR TITLE
Add support ruby 2.3

### PR DESCRIPTION
**Pull request by deivinsontejeda**
- Remove 'date/format' which is a empty file[1] no longer available on
  	recent Ruby's version.

Since Ruby Version 2.2 date/format file is not available. You can see the [changelog](https://github.com/ruby/ruby/blob/ruby_2_2/ChangeLog#L8232)

  [1] https://github.com/ruby/ruby/blob/ruby_2_1/ext/date/lib/date/format.rb

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
@deivinsontejeda Also getting this error. Would love to get this merged.

**Comment by deivinsontejeda** [comment]
@andreiglingeanu I think you can use this repo[1] where it's the fix, in fact I'm using it due to this PR is not merge yet 

[1] https://github.com/deivinsontejeda/runt/tree/fix-compatibility-ruby-2-3

**Comment by andreiglingeanu** [comment]
@deivinsontejeda Yeah, removing a require line is not that hard. Wondering why this is not getting merged.

**Comment by deivinsontejeda** [comment]
Sure. Few months ago I have emailing to @mlipper in order to know if this project is under maintenance or not. The answer was he was very busy on his work. :(

**Comment by andreiglingeanu** [comment]
Yeah, it may have a lot of useful use cases.

**Comment by mlipper** [comment]
Sorry for the delay. Let me try merging this once I get back up to speed with Ruby ecosystem and can set up a stable test environment. I'll try to complete this in the next few days.

**Comment by mlipper** [comment]
Ok, well that was easier than expected [1]. 

I'll merge this but could you please re-submit with the original Unix line feeds and remove several trailing spaces? Or could you please point me to the relevant git magic to allow me to do this easily and i'll merge from the command line?

I can remove fix the space issues myself but I figured you'd prefer to have the merge documented...
----
[1]: Running Ruby 2.3 at work means doing it through a corporate NTLMv2 proxy which means configuring HTTP/S and SOCKS5 proxying for pacman (MSYS2/MinGW64) and gems -- e.g. PIA). Luckily, CNTLM saved the day.

**Comment by deivinsontejeda** [comment]
It's just one line. I cannot see the trailing spaces. If you prefer send the fix yourself.

**Comment by mlipper** [comment]
No worries. I'll just merge your pull request and fix it afterwards. Thanks for your contribution and soory for the delay.

**Comment by mlipper** [comment]
Thanks for the contribution! Sorry for the delay.

**Pull request merged**
